version: '3.3'
services:
  portfolio-fe:
    build:
      context: .
    image: mbnatafgi/portfolio:fe
    container_name: portfolio-fe
    volumes:
      - portfolio-fe:/build
    env_file:
      - ./variables.env
volumes:
  portfolio-fe:
    external: true